 
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  postgres:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment:
        - POSTGRESQL_USERNAME=admin
        - POSTGRESQL_PASSWORD=admin
        - POSTGRESQL_DATABASE=yacht
      volumes:
        - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: yacht
    volumes:
      - mongo-data:/data/db
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - rabbitmq

  # user-microservice:
  #   build: ./microservices/user-service
  #   depends_on:
  #     - rabbitmq

  # auth-microservice:
  #   build: ./microservices/auth-service
  #   depends_on:
  #     - rabbitmq
volumes:
  local_pgdata:
  pgadmin-data:
  mongo-data: